// Copyright (C) 2018 GerritForge Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package jenkins.plugins.gerrit.workflow;

import com.google.gerrit.extensions.api.GerritApi;
import com.google.gerrit.extensions.api.changes.ChangeApi;
import com.google.gerrit.extensions.api.changes.Changes;
import com.google.gerrit.extensions.api.changes.NotifyHandling;
import com.google.gerrit.extensions.api.changes.ReviewInput;
import com.google.gerrit.extensions.api.changes.RevisionApi;
import com.google.gerrit.extensions.restapi.RestApiException;
import hudson.Extension;
import hudson.model.TaskListener;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import javax.annotation.Nonnull;
import jenkins.plugins.gerrit.GerritApiBuilder;
import jenkins.plugins.gerrit.GerritChange;
import jenkins.plugins.gerrit.GerritVersion;
import org.jenkinsci.plugins.workflow.steps.*;
import org.kohsuke.stapler.DataBoundConstructor;
import org.kohsuke.stapler.DataBoundSetter;

public class GerritReviewStep extends Step {
  @Deprecated private String label = "Verified";
  @Deprecated private int score;
  private Map<String, Integer> labels;
  private String message = "";
  private Optional<NotifyHandling> notify = Optional.empty();

  @DataBoundConstructor
  public GerritReviewStep() {}

  public static class Execution extends SynchronousNonBlockingStepExecution<Void> {
    private static final long serialVersionUID = 1L;

    private final String label;
    private final int score;
    private final Map<String, Integer> labels;
    private final String message;
    private final NotifyHandling notify;

    protected Execution(
        StepContext context,
        String label,
        int score,
        Map<String, Integer> labels,
        String message,
        NotifyHandling notify) {
      super(context);
      this.label = label;
      this.score = score;
      this.labels =
          labels == null ? null : Collections.unmodifiableMap(new LinkedHashMap<>(labels));
      this.message = message;
      this.notify = notify;
    }

    @Override
    protected Void run() throws Exception {
      GerritApi gerritApi =
          new GerritApiBuilder().stepContext(getContext()).requireAuthentication().build();
      if (gerritApi == null) {
        return null;
      }

      GerritChange change = new GerritChange(getContext());
      if (change.valid()) {
        ReviewInput reviewInput = new ReviewInput().message(message);
        boolean negativeVote = false;
        Map<String, Integer> effectiveLabels = labels;
        if (effectiveLabels == null && label != null) {
          effectiveLabels = Collections.singletonMap(label, score);
        }
        TaskListener listener = getContext().get(TaskListener.class);
        listener
            .getLogger()
            .format(
                "Gerrit review change %d/%d labels %s (%s)%n",
                change.getChangeId(), change.getRevision(), effectiveLabels, message);
        if (effectiveLabels != null) {
          for (Map.Entry<String, Integer> l : effectiveLabels.entrySet()) {
            reviewInput.label(l.getKey(), l.getValue());
            if (l.getValue() < 0) {
              negativeVote = true;
            }
          }
        }
        reviewInput.drafts = ReviewInput.DraftHandling.PUBLISH;
        reviewInput.tag = "autogenerated:jenkins";
        if (notify != null) {
          reviewInput.notify = notify;
        } else {
          String notifyProp = System.getProperty("gerrit.notify");
          if (notifyProp != null) {
            reviewInput.notify = NotifyHandling.valueOf(notifyProp);
          } else if (negativeVote) {
            reviewInput.notify = NotifyHandling.OWNER;
          }
        }
        RevisionApi revisionApi = getChangeApi(gerritApi, change).revision(change.getRevision());
        GerritStepInterruption.checkBeforeMutation();
        revisionApi.review(reviewInput);
      }
      return null;
    }
  }

  private static ChangeApi getChangeApi(GerritApi gerritApi, GerritChange change)
      throws RestApiException {
    Changes changesApi = gerritApi.changes();
    return GerritVersion.isVersionBelow215(gerritApi)
        ? changesApi.id(change.getChangeId())
        : changesApi.id(change.getProject(), change.getChangeId());
  }

  @Deprecated
  public int getScore() {
    return score;
  }

  @Deprecated
  @DataBoundSetter
  public void setScore(int score) {
    this.score = score;
  }

  public Map<String, Integer> getLabels() {
    return labels;
  }

  @DataBoundSetter
  public void setLabels(Map<String, Integer> labels) {
    this.labels = labels;
  }

  public String getMessage() {
    return message;
  }

  @DataBoundSetter
  public void setMessage(String message) {
    this.message = message;
  }

  @DataBoundSetter
  public void setNotify(NotifyHandling notify) {
    this.notify = Optional.ofNullable(notify);
  }

  public Optional<NotifyHandling> getNotify() {
    return notify;
  }

  @Deprecated
  public String getLabel() {
    return label;
  }

  @Deprecated
  @DataBoundSetter
  public void setLabel(String label) {
    this.label = label;
  }

  @Override
  public StepExecution start(StepContext stepContext) throws Exception {
    return new Execution(stepContext, label, score, labels, message, notify.orElse(null));
  }

  @Extension
  public static class DescriptorImpl extends StepDescriptor {

    @Override
    public Set<Class<?>> getRequiredContext() {
      return Collections.emptySet();
    }

    @Override
    public String getFunctionName() {
      return "gerritReview";
    }

    @Nonnull
    @Override
    public String getDisplayName() {
      return "Gerrit Review Label";
    }
  }
}
